// Every Language tesseract has a fast model for, by traineddata code. The
// names are what the picker shows; the codes are what the model files are
// called. Sorted by name, English first because it is the default.

export interface Language {
  code: string;
  name: string;
}

const RAW: [string, string][] = [
  ["eng", "English"],
  ["afr", "Afrikaans"],
  ["amh", "Amharic"],
  ["ara", "Arabic"],
  ["asm", "Assamese"],
  ["aze", "Azerbaijani"],
  ["aze_cyrl", "Azerbaijani (Cyrillic)"],
  ["bel", "Belarusian"],
  ["ben", "Bengali"],
  ["bod", "Tibetan"],
  ["bos", "Bosnian"],
  ["bre", "Breton"],
  ["bul", "Bulgarian"],
  ["cat", "Catalan"],
  ["ceb", "Cebuano"],
  ["ces", "Czech"],
  ["chi_sim", "Chinese (Simplified)"],
  ["chi_sim_vert", "Chinese (Simplified, vertical)"],
  ["chi_tra", "Chinese (Traditional)"],
  ["chi_tra_vert", "Chinese (Traditional, vertical)"],
  ["chr", "Cherokee"],
  ["cos", "Corsican"],
  ["cym", "Welsh"],
  ["dan", "Danish"],
  ["deu", "German"],
  ["div", "Dhivehi"],
  ["dzo", "Dzongkha"],
  ["ell", "Greek"],
  ["enm", "English (Middle)"],
  ["epo", "Esperanto"],
  ["est", "Estonian"],
  ["eus", "Basque"],
  ["fao", "Faroese"],
  ["fas", "Persian"],
  ["fil", "Filipino"],
  ["fin", "Finnish"],
  ["fra", "French"],
  ["frk", "German (Fraktur)"],
  ["frm", "French (Middle)"],
  ["fry", "Frisian (Western)"],
  ["gla", "Scottish Gaelic"],
  ["gle", "Irish"],
  ["glg", "Galician"],
  ["grc", "Greek (Ancient)"],
  ["guj", "Gujarati"],
  ["hat", "Haitian Creole"],
  ["heb", "Hebrew"],
  ["hin", "Hindi"],
  ["hrv", "Croatian"],
  ["hun", "Hungarian"],
  ["hye", "Armenian"],
  ["iku", "Inuktitut"],
  ["ind", "Indonesian"],
  ["isl", "Icelandic"],
  ["ita", "Italian"],
  ["ita_old", "Italian (Old)"],
  ["jav", "Javanese"],
  ["jpn", "Japanese"],
  ["jpn_vert", "Japanese (vertical)"],
  ["kan", "Kannada"],
  ["kat", "Georgian"],
  ["kat_old", "Georgian (Old)"],
  ["kaz", "Kazakh"],
  ["khm", "Khmer"],
  ["kir", "Kyrgyz"],
  ["kmr", "Kurdish (Kurmanji)"],
  ["kor", "Korean"],
  ["kor_vert", "Korean (vertical)"],
  ["lao", "Lao"],
  ["lat", "Latin"],
  ["lav", "Latvian"],
  ["lit", "Lithuanian"],
  ["ltz", "Luxembourgish"],
  ["mal", "Malayalam"],
  ["mar", "Marathi"],
  ["mkd", "Macedonian"],
  ["mlt", "Maltese"],
  ["mon", "Mongolian"],
  ["mri", "Maori"],
  ["msa", "Malay"],
  ["mya", "Burmese"],
  ["nep", "Nepali"],
  ["nld", "Dutch"],
  ["nor", "Norwegian"],
  ["oci", "Occitan"],
  ["ori", "Odia"],
  ["pan", "Punjabi"],
  ["pol", "Polish"],
  ["por", "Portuguese"],
  ["pus", "Pashto"],
  ["que", "Quechua"],
  ["ron", "Romanian"],
  ["rus", "Russian"],
  ["san", "Sanskrit"],
  ["sin", "Sinhala"],
  ["slk", "Slovak"],
  ["slv", "Slovenian"],
  ["snd", "Sindhi"],
  ["spa", "Spanish"],
  ["spa_old", "Spanish (Old)"],
  ["sqi", "Albanian"],
  ["srp", "Serbian"],
  ["srp_latn", "Serbian (Latin)"],
  ["sun", "Sundanese"],
  ["swa", "Swahili"],
  ["swe", "Swedish"],
  ["syr", "Syriac"],
  ["tam", "Tamil"],
  ["tat", "Tatar"],
  ["tel", "Telugu"],
  ["tgk", "Tajik"],
  ["tha", "Thai"],
  ["tir", "Tigrinya"],
  ["ton", "Tongan"],
  ["tur", "Turkish"],
  ["uig", "Uyghur"],
  ["ukr", "Ukrainian"],
  ["urd", "Urdu"],
  ["uzb", "Uzbek"],
  ["uzb_cyrl", "Uzbek (Cyrillic)"],
  ["vie", "Vietnamese"],
  ["yid", "Yiddish"],
  ["yor", "Yoruba"],
];

export const LANGUAGES: Language[] = RAW.map(([code, name]) => ({ code, name }));
LANGUAGES.sort((a, b) => (a.code === "eng" ? -1 : b.code === "eng" ? 1 : a.name.localeCompare(b.name)));

const BY_CODE = new Map(LANGUAGES.map((l) => [l.code, l.name]));

export function languageName(code: string): string {
  return BY_CODE.get(code) ?? code;
}
